categories:
  - name: "🍽️ Пищеварение"
    type: "text"
    emoji: "🍽️"
    color: "#00B894"
    description: "Состояние пищеварительной системы"
    order: 7

  - name: "💊 Физическое здоровье"
    type: "percent"
    emoji: "💊"
    color: "#FD79A8"
    description: "Общее физическое самочувствие"
    order: 8

  - name: "💭 Ментальная ясность"
    type: "scale_1_10"
    emoji: "💭"
    color: "#74B9FF"
    description: "Ясность мышления и умственная острота"
    order: 9

  - name: "🏃 Физическая активность"
    type: "percent"
    emoji: "🏃"
    color: "#55E6C1"
    description: "Уровень физической активности и упражнений"
    order: 10

  - name: "🍎 Питание"
    type: "scale_1_10"
    emoji: "🍎"
    color: "#FF9FF3"
    description: "Качество питания и пищевых привычек"
    order: 11

  - name: "💧 Гидратация"
    type: "percent"
    emoji: "💧"
    color: "#3867D6"
    description: "Потребление воды и уровень гидратации"
    order: 12

  - name: "🌞 Утренняя энергия"
    type: "percent"
    emoji: "🌞"
    color: "#FDCB6E"
    description: "Уровень энергии при пробуждении"
    order: 13

  - name: "🌙 Вечерняя энергия"
    type: "percent"
    emoji: "🌙"
    color: "#A29BFE"
    description: "Уровень энергии вечером"
    order: 14

  - name: "📚 Фокус на обучении"
    type: "scale_1_10"
    emoji: "📚"
    color: "#00CEC9"
    description: "Способность фокусироваться на учебных задачах"
    order: 15

  - name: "👥 Социальная энергия"
    type: "scale_1_10"
    emoji: "👥"
    color: "#F8A5C2"
    description: "Энергия для социальных взаимодействий"
    order: 16

  - name: "🎯 Мотивация"
    type: "scale_1_10"
    emoji: "🎯"
    color: "#546DE5"
    description: "Общая мотивация и драйв"
    order: 17

  - name: "🔄 Восстановление"
    type: "percent"
    emoji: "🔄"
    color: "#C44569"
    description: "Уровень восстановления тела и ума"
    order: 18

  - name: "🌿 Общее благополучие"
    type: "scale_1_10"
    emoji: "🌿"
    color: "#26DE81"
    description: "Общее ощущение благополучия"
    order: 19

  - name: "⚡ Пиковая производительность"
    type: "yes_no"
    emoji: "⚡"
    color: "#FED330"
    description: "Были ли вы сегодня на пике производительности?"
    order: 20