categories:
  - name: "💪 Энергия"
    type: "percent"
    emoji: "💪"
    color: "#FF6B6B"
    description: "Уровень физической энергии"
    order: 1
  - name: "🧠 Фокус"
    type: "scale_1_10"
    emoji: "🧠"
    color: "#4ECDC4"
    description: "Способность концентрироваться"
    order: 2
  - name: "😌 Настроение"
    type: "scale_1_10"
    emoji: "😌"
    color: "#FFD93D"
    description: "Эмоциональное состояние"
    order: 3
  - name: "🛌 Качество сна"
    type: "scale_1_10"
    emoji: "🛌"
    color: "#6C5CE7"
    description: "Как вы спали прошлой ночью"
    order: 4
  - name: "🍽️ Пищеварение"
    type: "text"
    emoji: "🍽️"
    color: "#00B894"
    description: "Состояние пищеварительной системы"
    order: 5
  - name: "❤️ Давление"
    type: "text"
    emoji: "❤️"
    color: "#E84393"
    description: "Артериальное давление"
    order: 6