categories:
  - name: "💪 Уровень энергии"
    type: "percent"
    emoji: "💪"
    color: "#FF6B6B"
    description: "Физическая энергия и жизненный тонус"
    order: 1

  - name: "🧠 Ментальная концентрация"
    type: "scale_1_10"
    emoji: "🧠"
    color: "#4ECDC4"
    description: "Способность к концентрации и фокусировке"
    order: 2

  - name: "😌 Настроение"
    type: "scale_1_10"
    emoji: "😌"
    color: "#FFD93D"
    description: "Общее эмоциональное состояние"
    order: 3

  - name: "🛌 Качество сна"
    type: "scale_1_10"
    emoji: "🛌"
    color: "#6C5CE7"
    description: "Насколько хорошо вы спали прошлой ночью"
    order: 4

  - name: "🧘 Уровень стресса"
    type: "scale_1_10"
    emoji: "🧘"
    color: "#E17055"
    description: "Текущий уровень стресса и напряжения"
    order: 5

  - name: "💼 Продуктивность"
    type: "percent"
    emoji: "💼"
    color: "#636E72"
    description: "Продуктивность на работе/учебе"
    order: 6